using System;using System.Collections;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;
public static class BoneclawReview20260920 {
 const string Key="BoneclawReview20260920";
 public static string Output => Environment.GetCommandLineArgs().Where(a=>a.StartsWith("--d06-output=")).Select(a=>Path.GetFullPath(a.Substring(13))).FirstOrDefault() ?? Path.GetFullPath("../output/ironclaw-tempest-20260918");
 public static void Begin(){SessionState.SetBool(Key,true);EditorSceneManager.OpenScene("Assets/Scenes/BattlePrototype.unity");EditorApplication.isPlaying=true;}
 [InitializeOnLoadMethod]static void Restore(){EditorApplication.playModeStateChanged+=s=>{if(!SessionState.GetBool(Key,false))return;if(s==PlayModeStateChange.EnteredPlayMode)new GameObject("D06 review").AddComponent<BoneclawReviewRunner20260920>();if(s==PlayModeStateChange.EnteredEditMode){SessionState.SetBool(Key,false);EditorApplication.Exit(0);}};}
}
[DefaultExecutionOrder(3000)]
public sealed class BoneclawReviewRunner20260920:MonoBehaviour{
 string output;UnityBattleBridge bridge;BattlePrototype battle;int hits;string capture;EnemyHandle actor;Quaternion[] rest;Transform[] joints;float maxAngle;
 void Log(string s,string stack,LogType type){if(s.Contains("combat-contact")&&s.Contains("enemy:clock-guard-primary"))hits++;}
 void Check(bool b,string s){if(!b){File.WriteAllText(output+"/failed.txt",s);Debug.LogError(s);EditorApplication.Exit(3);throw new Exception(s);}Debug.Log("D06_PASS "+s);}
 IEnumerator Start(){Application.logMessageReceived+=Log;Time.captureFramerate=30;output=BoneclawReview20260920.Output;Directory.CreateDirectory(output);yield return new WaitForSeconds(3);bridge=FindFirstObjectByType<UnityBattleBridge>();battle=FindFirstObjectByType<BattlePrototype>();
 Send("church-tower:clock-guard-primary@boneclaw");yield return new WaitForSeconds(.5f);Send("combat-start");actor=FindObjectsByType<EnemyHandle>(FindObjectsSortMode.None).Single(h=>battle.BelongsToCurrentEncounter(h));joints=actor.VisualRoot.GetComponentsInChildren<Transform>().Where(t=>t.name.StartsWith("UpperArm.")).ToArray();rest=joints.Select(t=>t.localRotation).ToArray();var home=actor.EnemyRoot.position;
 foreach(var intent in new[]{"tower_piercing_claw","tower_tail_sweep","tower_heavy_claw"}) {int before=hits;maxAngle=0;Send("enemy:clock-guard-primary:"+(intent=="tower_heavy_claw"?"tower_claw_charge":"tower_claw_charge"));for(int f=0;f<24;f++){capture=intent+"-"+f.ToString("D3");yield return null;}Send("enemy:clock-guard-primary:"+intent);for(int f=24;f<84;f++){capture=intent+"-"+f.ToString("D3");yield return null;}Check(hits==before+1,intent+" exactly one contact");Check(maxAngle>35,intent+" arm excursion "+maxAngle);Check(Vector3.Distance(home,actor.EnemyRoot.position)<.001f,"root does not drift");}
 foreach(float delay in new[]{.10f,.27f}){int before=hits;Send("enemy:clock-guard-primary:tower_heavy_claw");yield return new WaitForSeconds(delay);Send("combat-stop");yield return new WaitForSeconds(1);Check(hits==before,"stop before impact no late damage");Check(FindObjectsByType<ChurchFinalVfx20260917>(FindObjectsSortMode.None).Length==0,"stop cleans all owned visuals");Send("combat-start");}
 int previous=hits;Send("enemy:clock-guard-primary:tower_piercing_claw");yield return new WaitForSeconds(.1f);bridge.SetEnemyVisibility("clock-guard-primary=hidden");yield return new WaitForSeconds(1);Check(hits==previous,"death before hit cancels");bridge.SetEnemyVisibility("clock-guard-primary=visible");yield return new WaitForSeconds(.2f);Send("combat-start");Send("enemy:clock-guard-primary:tower_tail_sweep");yield return new WaitForSeconds(1.6f);Check(hits==previous+1,"retry contact once");Send("combat-stop");yield return null;Check(FindObjectsByType<ChurchFinalVfx20260917>(FindObjectsSortMode.None).Length==0,"final cleanup");File.WriteAllText(output+"/passed.txt","D06 three actions: one contact each; root stable; stop before contact and death cancel; retry works; visuals cleaned. Unity PlayMode, not phone verification.");EditorApplication.isPlaying=false;}
 void Send(string a){bridge.ApplyCommand("{\"action\":\""+a+"\"}");}
 void LateUpdate(){if(joints!=null)for(int i=0;i<joints.Length;i++)maxAngle=Mathf.Max(maxAngle,Quaternion.Angle(rest[i],joints[i].localRotation));if(capture==null)return;Capture(capture);capture=null;}
 void Capture(string name){var cam=Camera.main;var old=cam.targetTexture;var active=RenderTexture.active;float aspect=cam.aspect;var rt=new RenderTexture(720,1280,24);var image=new Texture2D(720,1280,TextureFormat.RGB24,false);try{cam.aspect=540f/960;typeof(BattlePrototype).GetMethod("FitRuntimeBackground",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(battle,new object[]{cam});cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,720,1280),0,0);image.Apply();File.WriteAllBytes(output+"/"+name+".png",image.EncodeToPNG());}finally{cam.targetTexture=old;cam.aspect=aspect;RenderTexture.active=active;Destroy(rt);Destroy(image);}}
 void OnDestroy(){Application.logMessageReceived-=Log;}
}
