using System;using System.Collections;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;
public static class SaltmawReview20260919 {
 const string Key="SaltmawReview20260919";
 public static string ReviewOutput { get { foreach(var arg in Environment.GetCommandLineArgs()) if(arg.StartsWith("--d02-output=")) return Path.GetFullPath(arg.Substring(13)); return Path.GetFullPath("../output/saltmaw-broad-20260919"); } }
 public static void Begin(){PrepareBlade();SessionState.SetBool(Key,true);EditorSceneManager.OpenScene("Assets/Scenes/BattlePrototype.unity");EditorApplication.isPlaying=true;}
 public static void PrepareBlade(){
  const string root="Assets/Resources/ChurchSpellArt/";AssetDatabase.Refresh();
  var ti=AssetImporter.GetAtPath(root+"SaltSpikeNormal.png") as TextureImporter;if(ti){ti.textureType=TextureImporterType.NormalMap;ti.SaveAndReimport();}
  var material=new Material(Shader.Find("Standard"));material.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>(root+"SaltSpikeColor.png");material.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>(root+"SaltSpikeNormal.png"));material.EnableKeyword("_NORMALMAP");material.SetFloat("_Metallic",0f);material.SetFloat("_Glossiness",.30f);
  var existing=AssetDatabase.LoadAssetAtPath<Material>(root+"SaltSpike.mat");if(existing){EditorUtility.CopySerialized(material,existing);UnityEngine.Object.DestroyImmediate(material);material=existing;}else AssetDatabase.CreateAsset(material,root+"SaltSpike.mat");
  var source=AssetDatabase.LoadAssetAtPath<GameObject>(root+"SaltSpikeMesh.fbx");var obj=UnityEngine.Object.Instantiate(source);obj.name="SaltSpike";var rends=obj.GetComponentsInChildren<Renderer>();var bounds=rends[0].bounds;foreach(var rr in rends)bounds.Encapsulate(rr.bounds);obj.transform.localScale*=2.2f/Mathf.Max(bounds.size.x,Mathf.Max(bounds.size.y,bounds.size.z));Debug.Log("BLADE_BOUNDS "+bounds+" scale "+obj.transform.localScale);foreach(var r in obj.GetComponentsInChildren<Renderer>())r.sharedMaterial=material;PrefabUtility.SaveAsPrefabAsset(obj,root+"SaltSpike.prefab");UnityEngine.Object.DestroyImmediate(obj);AssetDatabase.SaveAssets();
 }
 [InitializeOnLoadMethod]static void Restore(){EditorApplication.playModeStateChanged+=s=>{if(!SessionState.GetBool(Key,false))return;if(s==PlayModeStateChange.EnteredPlayMode)new GameObject("D02 review").AddComponent<SaltmawReviewRunner20260919>();if(s==PlayModeStateChange.EnteredEditMode){SessionState.SetBool(Key,false);EditorApplication.Exit(0);}};}
}
[DefaultExecutionOrder(3000)]
public sealed class SaltmawReviewRunner20260919:MonoBehaviour{
 string output;UnityBattleBridge bridge;BattlePrototype battle;int hits;string capture;EnemyHandle actor;Quaternion[] rest;Transform[] joints;float maxAngle;
 void Log(string s,string stack,LogType type){if(s.Contains("combat-contact")&&s.Contains("enemy:clock-guard-primary"))hits++;}
 void Check(bool b,string s){if(!b){File.WriteAllText(output+"/failed.txt",s);Debug.LogError(s);EditorApplication.Exit(3);throw new Exception(s);}Debug.Log("D02_PASS "+s);}
 IEnumerator Start(){Application.logMessageReceived+=Log;Time.captureFramerate=30;output=SaltmawReview20260919.ReviewOutput;Directory.CreateDirectory(output);yield return new WaitForSeconds(3);bridge=FindFirstObjectByType<UnityBattleBridge>();battle=FindFirstObjectByType<BattlePrototype>();
 Send("church-tower:clock-guard-primary@saltmaw");yield return new WaitForSeconds(.5f);Send("combat-start");actor=FindObjectsByType<EnemyHandle>(FindObjectsSortMode.None).Single(h=>battle.BelongsToCurrentEncounter(h));joints=actor.VisualRoot.GetComponentsInChildren<Transform>().Where(t=>t.name=="Neck"||t.name=="Chest").ToArray();rest=joints.Select(t=>t.localRotation).ToArray();Check(joints.Length==2,"chest and neck bound");var home=actor.EnemyRoot.position;
 foreach(var intent in new[]{"tower_poison","tower_salt_spike"}) {int before=hits;maxAngle=0;Send("enemy:clock-guard-primary:"+"tower_sac_charge");for(int f=0;f<24;f++){capture=intent+"-"+f.ToString("D3");yield return null;}Send("enemy:clock-guard-primary:"+intent);for(int f=24;f<84;f++){capture=intent+"-"+f.ToString("D3");yield return null;}Check(hits==before+1,intent+" exactly one contact");Check(maxAngle>5,intent+" visible arm movement "+maxAngle);Check(Vector3.Distance(home,actor.EnemyRoot.position)<.001f,"root does not drift");}
 foreach(float delay in new[]{.10f,.27f}){int before=hits;Send("enemy:clock-guard-primary:tower_salt_spike");yield return new WaitForSeconds(delay);Send("combat-stop");yield return new WaitForSeconds(1);Check(hits==before,"stop before impact no late damage");Check(FindObjectsByType<SaltmawSpell20260919>(FindObjectsSortMode.None).Length==0,"stop cleans all owned visuals");Send("combat-start");}
 int previous=hits;Send("enemy:clock-guard-primary:tower_poison");yield return new WaitForSeconds(.1f);bridge.SetEnemyVisibility("clock-guard-primary=hidden");yield return new WaitForSeconds(1);Check(hits==previous,"death before hit cancels");bridge.SetEnemyVisibility("clock-guard-primary=visible");yield return new WaitForSeconds(.2f);Send("combat-start");Send("enemy:clock-guard-primary:tower_salt_spike");yield return new WaitForSeconds(1.6f);Check(hits==previous+1,"retry contact once");Send("combat-stop");yield return null;Check(FindObjectsByType<SaltmawSpell20260919>(FindObjectsSortMode.None).Length==0,"final cleanup");File.WriteAllText(output+"/passed.txt","D02 two actions: one contact each; chest and neck move >5 degrees; root stable; stop before contact and death cancel; retry works; visuals cleaned. Unity PlayMode, not phone verification.");EditorApplication.isPlaying=false;}
 void Send(string a){bridge.ApplyCommand("{\"action\":\""+a+"\"}");}
 void LateUpdate(){if(joints!=null)for(int i=0;i<joints.Length;i++)maxAngle=Mathf.Max(maxAngle,Quaternion.Angle(rest[i],joints[i].localRotation));if(capture==null)return;Capture(capture);capture=null;}
 void Capture(string name){var cam=Camera.main;var old=cam.targetTexture;var active=RenderTexture.active;float aspect=cam.aspect;var rt=new RenderTexture(720,1280,24);var image=new Texture2D(720,1280,TextureFormat.RGB24,false);try{cam.aspect=540f/960;typeof(BattlePrototype).GetMethod("FitRuntimeBackground",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(battle,new object[]{cam});cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,720,1280),0,0);image.Apply();File.WriteAllBytes(output+"/"+name+".png",image.EncodeToPNG());}finally{cam.targetTexture=old;cam.aspect=aspect;RenderTexture.active=active;Destroy(rt);Destroy(image);}}
 void OnDestroy(){Application.logMessageReceived-=Log;}
}
