using UnityEngine;
using System.Collections.Generic;
// Authored metal volumes inspired by the concept sheet; parent owns lifetime/contact.
public sealed class BountyForgedSpell20260921:MonoBehaviour {
 readonly List<Material> mats=new List<Material>(); readonly List<Transform> parts=new List<Transform>();Transform body;string kind;bool guard;
 Material Metal(Color c,bool glow=false){var m=new Material(glow?Shader.Find("Standard"):Resources.Load<Shader>("Shaders/ForgedMetal20260921"));m.color=c;m.SetFloat("_Metallic",.85f);m.SetFloat("_Glossiness",.72f);if(glow){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",c*2);}mats.Add(m);return m;}
 Transform Box(Transform parent,string name,Vector3 p,Vector3 scale,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);Destroy(g.GetComponent<Collider>());g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=p;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;return g.transform;}
 Transform Plate(Transform parent,Material m){var g=new GameObject("Beveled engraved plate");g.transform.SetParent(parent,false);var mesh=new Mesh();Vector2[] shape={new Vector2(-.4f,.65f),new Vector2(.4f,.65f),new Vector2(.52f,-.25f),new Vector2(0,-.65f),new Vector2(-.52f,-.25f)};var v=new List<Vector3>();for(int z=0;z<2;z++)foreach(var p in shape)v.Add(new Vector3(p.x,p.y,z==0?-.12f:.12f));var ix=new List<int>();for(int i=1;i<4;i++){ix.AddRange(new[]{0,i+1,i,5,5+i,6+i});}for(int i=0;i<5;i++){int n=(i+1)%5;ix.AddRange(new[]{i,n,n+5,i,n+5,i+5});}mesh.SetVertices(v);mesh.SetTriangles(ix,0);mesh.RecalculateNormals();for(int k=0;k<5;k++){Vector3 a=v[k],b=v[(k+1)%5];var rail=Box(g.transform,"Raised silver border",(a+b)*.5f-Vector3.forward*.025f,new Vector3(.045f,(b-a).magnitude,.055f),Metal(new Color(.48f,.55f,.6f)));rail.localRotation=Quaternion.FromToRotation(Vector3.up,b-a);var bolt=GameObject.CreatePrimitive(PrimitiveType.Sphere);Destroy(bolt.GetComponent<Collider>());bolt.transform.SetParent(g.transform,false);bolt.transform.localPosition=a*.83f-Vector3.forward*.065f;bolt.transform.localScale=Vector3.one*.085f;bolt.GetComponent<Renderer>().sharedMaterial=rail.GetComponent<Renderer>().sharedMaterial;}g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=m;return g.transform;}
 public void Build(string species,bool defensive){kind=species;guard=defensive;body=new GameObject("Forged spell body").transform;body.SetParent(transform,false);var steel=Metal(new Color(.12f,.18f,.22f));var brass=Metal(new Color(.65f,.39f,.13f));var silver=Metal(new Color(.62f,.74f,.78f));var glow=Metal(kind=="b04"?new Color(.18f,.9f,.55f):new Color(.25f,.72f,1),true);
 if(guard){for(int i=0;i<6;i++){var plate=Plate(body,steel);parts.Add(plate);Box(plate,"Anchor stem",new Vector3(0,0,-.145f),new Vector3(.055f,.66f,.045f),silver);for(int s=-1;s<=1;s+=2)Box(plate,"Anchor fluke",new Vector3(s*.12f,-.22f,-.15f),new Vector3(.3f,.06f,.04f),silver).localRotation=Quaternion.Euler(0,0,s*30);for(int k=-1;k<=1;k+=2)Box(plate,"Charged edge",new Vector3(k*.37f,.12f,-.14f),new Vector3(.025f,.72f,.025f),glow);}}
 else{var head=Plate(body,kind=="b04"?brass:steel);head.localScale=new Vector3(.9f,1.7f,1.8f);Box(head,"Incised luminous spine",new Vector3(0,0,-.145f),new Vector3(.045f,1.0f,.045f),glow);for(int s=-1;s<=1;s+=2){var blade=Plate(body,kind=="b04"?brass:silver);blade.localPosition=new Vector3(s*.42f,.14f,0);blade.localScale=new Vector3(.48f,.65f,.8f);blade.localRotation=Quaternion.Euler(0,s*20,s*-42);parts.Add(blade);} }
 for(int i=0;i<18;i++){var link=new GameObject("Articulated metal link").transform;link.SetParent(body,false);for(int s=-1;s<=1;s+=2){Box(link,"Link rail",new Vector3(s*.10f,0,0),new Vector3(.045f,.28f,.06f),silver);Box(link,"Link bridge",new Vector3(0,s*.14f,0),new Vector3(.22f,.045f,.06f),silver);}parts.Add(link);}
 }
 public void Draw(Vector3 source,Vector3 target,float age,float contact){float f=Mathf.Clamp01(age/contact),post=Mathf.Max(0,age-contact);body.gameObject.SetActive(guard||post<.08f);if(!body.gameObject.activeSelf)return;body.position=guard?source:Vector3.Lerp(source,target,f*f*(3-2*f));body.rotation=guard?(Camera.main?Camera.main.transform.rotation:Quaternion.identity):Quaternion.FromToRotation(Vector3.down,(target-source).normalized);float t=guard?Time.time:age;int start=guard?6:2;
 for(int i=0;i<start;i++){var p=parts[i];if(guard){float a=i*Mathf.PI/3+t*.25f;p.localPosition=new Vector3(Mathf.Cos(a)*1.05f,Mathf.Sin(a)*1.28f,-.25f+Mathf.Sin(a)*.18f);p.localRotation=Quaternion.Euler(Mathf.Sin(t+i)*8,Mathf.Cos(t+i)*12,-a*Mathf.Rad2Deg+90);p.localScale=Vector3.one*.8f;}else p.localRotation=Quaternion.Euler(0,(i==0?-1:1)*(20+Mathf.Sin(t*6)*12),(i==0?42:-42));}
 for(int i=start;i<parts.Count;i++){float q=(i-start)/17f;parts[i].localPosition=guard?new Vector3(Mathf.Cos(q*Mathf.PI*2)*1.25f,Mathf.Sin(q*Mathf.PI*2)*1.5f,.06f):new Vector3(Mathf.Sin(q*8-t*5)*.19f,q*2.4f+.65f,Mathf.Sin(q*5)*.2f);parts[i].localRotation=Quaternion.Euler(0,i%2*75,guard?-q*360:Mathf.Sin(q*8-t*5)*18);parts[i].localScale=Vector3.one*.7f;}}
 void OnDestroy(){foreach(var m in mats)if(m)Destroy(m);foreach(var f in GetComponentsInChildren<MeshFilter>())if(f.sharedMesh&&f.gameObject.name=="Beveled engraved plate")Destroy(f.sharedMesh);}
}
